### ISSUE TITLE
Measure line labels not always on top

### ISSUE THREAD

**Issue by GoogleCodeExporter** [MassGIS/morisoliver#232]
```
They are on top of any basemap, which is good at least.  But they are under the 
3 tile overlays "Structures", "Tax Parcels", "Detailed Features".  They are 
also under vector data and raster data.  I also see the problem in IE 8 with 
Windows Server 2008.  So it broke somewhere along the line I guess, and it's 
not browser type or version specific.  The buffers shapes are OK - they are on 
top of everything.  We did have Charlton make a change on Sept. 12 which fixed 
the basemaps _printing_ on top of other data.
Not sure if that was a factor?
```

Original issue reported on code.google.com by `Aleda.Fr...@state.ma.us` on 5 Dec 2013 at 4:12

**Comment by MassGIS** [comment]
Aleda 11/12/2015 Still an issue in FF 42, IE 11 and Chrome 46.

**Comment by cgalvarino** [comment]
@MassGIS I thought I'd warm back up w/ this one, but I can't seem to trip it up.  Could you outline a few steps to reproduce it?

![snag-0037](https://cloud.githubusercontent.com/assets/180985/15682879/a68da33c-272d-11e6-9f05-5c26fe105293.jpg)

**Comment by MassGIS** [comment]
It looks like you have tiles only in the map and the labels are probably on top of those.  I would try some vector data.  For example, open OLIVER and measure - you'll see measurements no problem.  But then add the layer Shellfish Growing Areas (I picked that one because there are solid color polygons, but not completely covering the map).  Zoom into near a polygon and start to measure.  You'll see that the labels go UNDER the polygons.  I've attached a screenshot showing this.
![label_obscured_by_vector_data](https://cloud.githubusercontent.com/assets/10077576/15683100/b98a0c2c-272e-11e6-8c6b-268760228be7.PNG)
